[workspace]
members = ["aoc", "2022/day1", "2022/day2", "2022/day3", "2022/day4", "2023/01", "2023/02", "2023/03", "2023/04"]
resolver = "2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
debug = false
strip = true
